
import sys
import telnetlib
import time

tn = telnetlib.Telnet('192.168.1.50',5038,10)
tn.write("Action: Login\r\n")
tn.write("UserName: admin\r\n")
tn.write("Secret: amp111\r\n\r\n")
tn.write("Action: DongleSendUSSD\r\n")
tn.write("Device: dongle0\r\n")
tn.write("USSD: *102#\r\n\r\n")
time.sleep(10)
tn.write("Action: Logoff\r\n\r\n")

print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()
print tn.read_some()

		#self.tn.read_until("AppData: Incoming USSD:")
		#self.mensaje=self.tn.read_until("Uniqueid:")
		#self.tn.write("Action: Logoff\r\n\r\n")
		#self.mensaje=self.mensaje[:-10]
		#self.mensaje=self.tn.read_some()
		#self.mensaje="\nholi<br>holaaa<br>plap"

